language: go
go_import_path: github.com/getamis/istanbul-tools
os: linux
dist: trusty
go:
  - 1.7.6
  - 1.8.3
env:
  - TEST=tests/functional
  - TEST=tests/quorum

services:
  - docker

before_install:
  - docker pull quay.io/amis/constellation:latest
  - docker pull quay.io/amis/geth:istanbul_develop
  - docker pull quay.io/amis/quorum:latest

install:
  - go get github.com/Masterminds/glide
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - travis_wait 120 go test -v $(glide novendor | grep -v "\.\/tests\/\.\.\.") --timeout 120m && cd ${TRAVIS_BUILD_DIR}/${TEST} && travis_wait 120 ginkgo -r --progress

notifications:
    slack: maicoin:p2HicxEGvZveE900zgacSYwL
